sudo: required
services: 
  - docker

before_install:
  - docker build -t kremenovic96/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kremenovic96/react-test npm test

after_success:
  - docker build -t kremenovic96/prod-client ./client
  - docker build -t kremenovic96/prod-nginx ./nginx
  - docker build -t kremenovic96/prod-server ./server
  - docker build -t kremenovic96/prod-worker ./worker
 # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
  - docker push kremenovic96/prod-client
  - docker push kremenovic96/prod-nginx
  - docker push kremenovic96/prod-server
  - docker push kremenovic96/prod-worker